---
version: "3"
 
services:
    python-dev:
        container_name: python-dev-container
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/home
        tty: true